# Generated by Django 5.2.13 on 2026-05-03 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('appointment_type', models.CharField(choices=[('IN_PERSON', 'In Person'), ('TELECONSULT', 'Teleconsultation')], default='IN_PERSON', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, verbose_name='Reason for Visit')),
                ('doctor_notes', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('mpesa_reference', models.CharField(blank=True, max_length=50, verbose_name='M-Pesa Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'unique_together': {('doctor', 'date', 'start_time')},
            },
        ),
    ]
