# Generated by Django 5.2.13 on 2026-05-03 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('GP', 'General Practitioner'), ('PEDIATRICS', 'Pediatrics'), ('SURGERY', 'Surgery'), ('GYNECOLOGY', 'Gynecology'), ('CARDIOLOGY', 'Cardiology'), ('ORTHOPEDICS', 'Orthopedics'), ('PSYCHIATRY', 'Psychiatry'), ('DERMATOLOGY', 'Dermatology'), ('OTHER', 'Other')], default='GP', max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('years_of_exp', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
